"""empty message

Revision ID: 0739c753ae9d
Revises: 0a061626b871
Create Date: 2017-07-17 18:44:52.436665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0739c753ae9d'
down_revision = '0a061626b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('gpa', sa.Integer(), nullable=True))
    op.drop_constraint('user_password_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_password_key', 'user', ['password'])
    op.drop_column('goal', 'gpa')
    # ### end Alembic commands ###
