"""empty message

Revision ID: 6eb957a9f8a4
Revises: c7bbe8b4f1b4
Create Date: 2017-07-18 21:26:51.477630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb957a9f8a4'
down_revision = 'c7bbe8b4f1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major', sa.Column('credits_needed', sa.Integer(), nullable=True))
    op.add_column('major', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'major', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('total_credits_needed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_credits_needed')
    op.drop_constraint(None, 'major', type_='foreignkey')
    op.drop_column('major', 'user_id')
    op.drop_column('major', 'credits_needed')
    # ### end Alembic commands ###
