"""empty message

Revision ID: 7ba73ae112e3
Revises: 6eb957a9f8a4
Create Date: 2017-07-19 18:23:02.435683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba73ae112e3'
down_revision = '6eb957a9f8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_course')
    op.drop_column('course', 'university_id')
    #op.drop_constraint('user_university_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'university_id')
    op.drop_table('university')
    op.add_column('course', sa.Column('actual_grade', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('anticipated_grade', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('user_id', sa.Integer(), nullable=True))
    #op.drop_constraint('course_university_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_university_id_fkey', 'user', 'university', ['university_id'], ['id'])
    op.add_column('course', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_university_id_fkey', 'course', 'university', ['university_id'], ['id'])
    op.drop_column('course', 'user_id')
    op.drop_column('course', 'anticipated_grade')
    op.drop_column('course', 'actual_grade')
    op.create_table('university',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('university_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='university_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('anticipated_grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='user_course_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_course_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_course_pkey')
    )
    # ### end Alembic commands ###
