"""empty message

Revision ID: 803ddc9e5658
Revises: bac11e3c6338
Create Date: 2017-07-21 13:55:06.618314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803ddc9e5658'
down_revision = 'bac11e3c6338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    # ### end Alembic commands ###
