"""empty message

Revision ID: bac11e3c6338
Revises: 4ea5a70a0f11
Create Date: 2017-07-20 16:25:32.174331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac11e3c6338'
down_revision = '4ea5a70a0f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_course',
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major_course')
    # ### end Alembic commands ###
